remove state updating because we are unmounting the component anyway
Tenderize/tender-app pull request #179
Opened 2022-01-18 17:06 UTC by vujevits

Turning off the spinner is not needed because the component will be unmounted. Resolves react warning.

2022-01-18 17:47 UTC, kyriediculous commented
Does this fix not being able to connect from a route e.g. `stakers/graph`?

2022-01-18 19:34 UTC, kyriediculous commented
Looks like the error when trying to connect a wallet when not on the base route still persists but the memory-leak is fixed 
![image](https://user-images.githubusercontent.com/22256858/150006236-14923cb5-2b46-49ce-a1a2-bd605a7d470a.png)

2022-01-18 19:35 UTC, kyriediculous requested changes
^

2022-01-18 19:43 UTC, vujevits commented
> ^

this PR is not trying to fix that, it's unrelated. Fixing that in another PR.

2022-01-19 09:24 UTC, kyriediculous commented
They are related from my POV. The memory leak is because we are trying to update the state on an unmounted component, the unmounted component are the ones we need to connect the wallet.

2022-01-19 09:36 UTC, vujevits commented
> They are related from my POV. The memory leak is because we are trying to update the state on an unmounted component, the unmounted component are the ones we need to connect the wallet.

I mean these are two unrelated errors. The one fixed here we have since day1.

2022-01-19 09:41 UTC, kyriediculous approved these changes

2022-01-19 09:50 UTC, merged