Enable Audius
Tenderize/tender-app pull request #274
Opened 2022-05-24 11:31 UTC by reubenr0d

2022-05-24 13:39 UTC, vmaark commented on packages/shared/src/data/stakers.tsx
> +    hasPermit: true,
Cool!

2022-05-24 13:44 UTC, vmaark approved these changes
👍

2022-07-04 12:30 UTC, kyriediculous requested changes
There's a merge conflict in this, good spot that AUDIO has Permit support. 

Let's resolve the merge conflict , after that GTG 🚢

2022-07-05 16:32 UTC, vmaark approved these changes
👍

2022-07-05 16:38 UTC, kyriediculous approved these changes
LGTM 👍

2022-07-05 16:39 UTC, merged